### ISSUE TITLE
Does not work with many networks

### ISSUE THREAD

**Issue by Isopach** [Thom-x/stackoverflow-fanatic#7]
As seen from my code https://github.com/Isopach/stackoverflow-fanatic/blob/master/script.js#L9-L34
and comparing with my [network profile](https://stackexchange.com/users/5577005/yuu?tab=accounts), it does not seem to work for beyond 3-4 networks. 

With over 20 sites (counting meta separately), I only get logins to 3 of them (SO, Japanese SO and Japanese SO meta). 

Any idea of what might be causing this problem?

**Comment by Thom-x** [comment]
I don't now, any error log ?

**Comment by Isopach** [comment]
No, there's no error log and the logs don't show any anomaly. Maybe the problem is on stackexchange's side not detecting too many sites?

**Comment by Isopach** [comment]
I found a workaround to this problem. Since each instance seems to have a limit of 3 sites, deploy as many instances as `(number of sites) % 3 + 1` and edit the URL list accordingly.
